import { useEffect, useMemo, useState } from 'react'
import {
  Activity, AlertTriangle, ArrowRight, BarChart3, Brain, CalendarDays, Check, CheckCircle2,
  CheckSquare2, ChevronDown, Circle, Clock3, Flame, Goal as GoalIcon, HeartPulse, ListFilter,
  Download, Moon, MoreHorizontal, Plus, RefreshCw, Settings2, ShieldCheck, Sparkles, Sun, Target, Trash2, TrendingUp, UserX, X,
} from 'lucide-react'
import { api, downloadAccountExport, session } from '../lib/api'
import { calendarDateInTimeZone, dateTimeLocalValue, naiveDateTimeFromInput } from '../lib/datetime'
import type { ThemePreference } from '../lib/theme'
import type { AIConsent, Analytics, Balance, Goal, GoalPlan, GoalPlanPayload, Habit, Recommendation, Settings, Task, User } from '../types'
import { Empty, Loading, Modal, PageHeader } from './UI'
import { PrivacyPolicy } from './PrivacyPolicy'

const ruDate = (value?:string, withTime=false) => value ? new Intl.DateTimeFormat('ru-RU', withTime?{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}:{day:'numeric',month:'short'}).format(new Date(value)) : 'Без срока'
const priorityLabel:Record<string,string>={urgent:'Срочно',high:'Важно',medium:'Обычно',low:'Низкий'}

function Metric({icon:Icon,color,value,label,note}:{icon:typeof Activity;color:string;value:string|number;label:string;note:string}){return <div className="metric-card"><span className={`metric-icon ${color}`}><Icon/></span><div><b>{value}</b><span>{label}</span><small>{note}</small></div></div>}
function CardHead({icon:Icon,title,subtitle,action}:{icon:typeof Activity;title:string;subtitle:string;action?:React.ReactNode}){return <div className="card-head"><div><span><Icon/></span><div><h3>{title}</h3><small>{subtitle}</small></div></div>{action}</div>}

function TaskModal({timezone,onClose,onSaved}:{timezone:string;onClose:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState({title:'',due_at:dateTimeLocalValue(new Date(),timezone),reminder_at:'',priority:'medium',estimate_minutes:30,energy:'medium',project:''})
  const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await api('/tasks',{method:'POST',body:JSON.stringify({...form,due_at:naiveDateTimeFromInput(form.due_at),reminder_at:form.reminder_at?naiveDateTimeFromInput(form.reminder_at):null})});onSaved()}catch(err){setError(err instanceof Error?err.message:'Ошибка')}finally{setSaving(false)}}
  return <Modal title="Новая задача" onClose={onClose}><form className="modal-form" onSubmit={submit}><label className="full">Что нужно сделать?<input autoFocus required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Например, подготовить презентацию"/></label><label>Срок<input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label>Напомнить<input type="datetime-local" value={form.reminder_at} onChange={e=>setForm({...form,reminder_at:e.target.value})}/></label><label>Приоритет<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Низкий</option><option value="medium">Обычный</option><option value="high">Важный</option><option value="urgent">Срочный</option></select></label><label>Оценка, минут<input type="number" min="5" max="1440" value={form.estimate_minutes} onChange={e=>setForm({...form,estimate_minutes:+e.target.value})}/></label><label>Проект<input value={form.project} onChange={e=>setForm({...form,project:e.target.value})} placeholder="Личное"/></label>{error&&<div className="form-error full">{error}</div>}<div className="modal-actions full"><button type="button" className="secondary" onClick={onClose}>Отмена</button><button className="primary" disabled={saving}>{saving?'Сохраняем…':'Создать задачу'}</button></div></form></Modal>
}

export function TasksPage({timezone,onChanged}:{timezone:string;onChanged:()=>void}){
  const [tasks,setTasks]=useState<Task[]|null>(null);const [filter,setFilter]=useState('open');const [modal,setModal]=useState(false)
  const load=()=>api<Task[]>('/tasks').then(setTasks);useEffect(()=>{void load()},[])
  const visible=useMemo(()=>tasks?.filter(t=>filter==='all'||filter==='done'?t.status===filter:t.status!=='done'&&t.status!=='cancelled'),[tasks,filter])
  const update=async(task:Task,status:string)=>{await api(`/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({status})});load();onChanged()}
  const remove=async(id:number)=>{if(confirm('Удалить задачу?')){await api(`/tasks/${id}`,{method:'DELETE'});load();onChanged()}}
  if(!tasks)return <Loading/>
  return <div className="page"><PageHeader eyebrow="Ясные следующие шаги" title="Задачи" description="Соберите обязательства в одном месте и выбирайте по важности и ресурсу." action={<button className="primary" onClick={()=>setModal(true)}><Plus/> Новая задача</button>}/>
    <div className="task-toolbar"><div><ListFilter/><button className={filter==='open'?'active':''} onClick={()=>setFilter('open')}>Открытые <span>{tasks.filter(t=>t.status!=='done'&&t.status!=='cancelled').length}</span></button><button className={filter==='done'?'active':''} onClick={()=>setFilter('done')}>Готово</button><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Все</button></div><span>{tasks.filter(t=>t.status==='done').length} завершено</span></div>
    <section className="card task-list">{visible?.length?visible.map(task=><article className={`task-row ${task.status==='done'?'done':''}`} key={task.id}><button className="big-check" onClick={()=>update(task,task.status==='done'?'todo':'done')}>{task.status==='done'?<Check/>:<Circle/>}</button><div className="task-main"><b>{task.title}</b><span>{task.project||'Без проекта'} · {task.estimate_minutes} мин · энергия: {task.energy}</span></div><div className="task-meta"><em className={`priority ${task.priority}`}>{priorityLabel[task.priority]}</em><span><Clock3/>{ruDate(task.due_at,true)}</span></div><button className="icon-btn danger" onClick={()=>remove(task.id)}><Trash2/></button></article>):<Empty icon={CheckCircle2} title={filter==='done'?'Пока нет завершённых':'Список чист'} text={filter==='done'?'Завершённые задачи появятся здесь.':'Можно выбрать одну важную задачу и начать с неё.'}/>}</section>
    {modal&&<TaskModal timezone={timezone} onClose={()=>setModal(false)} onSaved={()=>{setModal(false);load();onChanged()}}/>}
  </div>
}

export function GoalsPage({timezone,onChanged}:{timezone:string;onChanged:()=>void}){
  const [goals,setGoals]=useState<Goal[]|null>(null);const [plans,setPlans]=useState<Record<number,GoalPlan|null>>({});const [modal,setModal]=useState(false);const [working,setWorking]=useState<number|null>(null);const [preview,setPreview]=useState<{goal:Goal;plan:GoalPlan}|null>(null);const [consentRequest,setConsentRequest]=useState<{goal:Goal;regenerate:boolean;consent:AIConsent}|null>(null);const [error,setError]=useState('')
  const load=async()=>{const items=await api<Goal[]>('/goals');setGoals(items);const rows=await Promise.all(items.map(async goal=>[goal.id,await api<GoalPlan>(`/goals/${goal.id}/plan`).catch(()=>null)] as const));setPlans(Object.fromEntries(rows))}
  useEffect(()=>{void load()},[])
  const runGenerate=async(goal:Goal,regenerate=false)=>{setWorking(goal.id);setError('');try{const plan=await api<GoalPlan>(`/goals/${goal.id}/${regenerate?'regenerate-plan':'generate-plan'}`,{method:'POST',body:JSON.stringify({reason:regenerate?'Изменились условия или пользователь запросил пересмотр':undefined})});setPlans(prev=>({...prev,[goal.id]:plan}))}catch(err){setError(err instanceof Error?err.message:'Не удалось составить план')}finally{setWorking(null)}}
  const generate=async(goal:Goal,regenerate=false)=>{setError('');try{const consent=await api<AIConsent>('/settings/ai-consent');if(consent.required&&!consent.active){setConsentRequest({goal,regenerate,consent});return}await runGenerate(goal,regenerate)}catch(err){setError(err instanceof Error?err.message:'Не удалось проверить настройки AI')}}
  const acceptConsentAndGenerate=async()=>{if(!consentRequest)return;const request=consentRequest;const accepted=await api<AIConsent>('/settings/ai-consent',{method:'POST',body:JSON.stringify({accepted:true,policy_version:request.consent.policy_version})});if(!accepted.active)throw new Error('Не удалось сохранить согласие');setConsentRequest(null);void runGenerate(request.goal,request.regenerate)}
  const toggleStep=async(goal:Goal,stepId:number,done:boolean)=>{await api(`/goals/${goal.id}/steps/${stepId}`,{method:'PATCH',body:JSON.stringify({is_completed:done})});load();onChanged()}
  const remove=async(id:number)=>{if(confirm('Удалить цель вместе с планом?')){await api(`/goals/${id}`,{method:'DELETE'});load();onChanged()}}
  const editPlan=async(goal:Goal,plan:GoalPlan)=>{const strategy=window.prompt('Измените стратегию плана',plan.plan.strategy);if(!strategy?.trim())return;const updated=await api<GoalPlan>(`/goals/${goal.id}/plan`,{method:'PATCH',body:JSON.stringify({plan:{...plan.plan,strategy:strategy.trim()},reason:'Стратегия изменена пользователем'})});setPlans(prev=>({...prev,[goal.id]:updated}))}
  const cancelPlan=async(goal:Goal)=>{await api(`/goals/${goal.id}/plan/cancel`,{method:'POST'});setPlans(prev=>({...prev,[goal.id]:prev[goal.id]?{...prev[goal.id]!,status:'cancelled'}:null}))}
  if(!goals)return <Loading/>
  return <div className="page"><PageHeader eyebrow="Направление важнее скорости" title="Цели" description="Превращайте большие намерения в понятные этапы и следите за реальным прогрессом." action={<button className="primary" onClick={()=>setModal(true)}><Plus/> Новая цель</button>}/>
    {error&&<div className="goal-ai-error"><AlertTriangle/>{error}</div>}
    <div className="goals-layout">{goals.length?goals.map((goal,index)=>{const plan=plans[goal.id];return <article className="goal-card" key={goal.id}><div className="goal-card-top"><span className={`goal-symbol g${index%3}`}><GoalIcon/></span><div className="goal-title"><span>{goal.horizon==='month'?'На месяц':goal.horizon==='year'?'На год':goal.horizon==='long_term'?'Долгосрочно':'На квартал'}</span><h3>{goal.title}</h3><p>{goal.description||'Без дополнительного описания'}</p></div><button className="icon-btn danger" onClick={()=>remove(goal.id)}><Trash2/></button></div><div className="goal-progress"><div><span>Прогресс</span><b>{goal.progress}%</b></div><div className="progress"><i style={{width:`${goal.progress}%`}}/></div><small>{goal.target_date?`Ориентир: ${ruDate(goal.target_date)}`:'Без жёсткого срока'}</small></div>
      {working===goal.id?<div className="goal-ai-loading"><i/><b>AI составляет план</b><span>Учитываю срок, расписание, привычки и текущую нагрузку…</span></div>:plan&&plan.status!=='cancelled'?<GoalAIPlan plan={plan} onApply={()=>setPreview({goal,plan})} onEdit={()=>void editPlan(goal,plan)} onRegenerate={()=>void generate(goal,true)} onDiscuss={()=>window.dispatchEvent(new Event('axel:open-ai'))} onCancel={()=>void cancelPlan(goal)}/>:<div className="goal-ai-empty"><Sparkles/><div><b>{plan?.status==='cancelled'?'Черновик отменён':'AI-план пока не создан'}</b><p>Запустите составление, когда AI-провайдер доступен.</p></div><button onClick={()=>void generate(goal,Boolean(plan))}><Sparkles/> Составить план</button></div>}
      {goal.steps.length>0&&<div className="goal-steps"><div className="steps-head"><b>Применённые этапы</b></div>{goal.steps.map(step=><button className={step.is_completed?'complete':''} key={step.id} onClick={()=>toggleStep(goal,step.id,!step.is_completed)}><i>{step.is_completed?<Check/>:<Circle/>}</i><span>{step.title}<small>{step.due_date?`до ${ruDate(step.due_date)}`:'без срока'}</small></span></button>)}</div>}
    </article>}):<div className="card"><Empty icon={Target} title="Добавьте первую цель" text="Сформулируйте желаемый результат — черновик плана составит Axel AI."/></div>}</div>
    {modal&&<GoalModal timezone={timezone} onClose={()=>setModal(false)} onSaved={()=>{setModal(false);load();onChanged()}}/>}
    {preview&&<PlanApplyModal goal={preview.goal} plan={preview.plan} onClose={()=>setPreview(null)} onApplied={()=>{setPreview(null);void load();onChanged()}}/>}
    {consentRequest&&<GoalAIConsentModal consent={consentRequest.consent} onClose={()=>setConsentRequest(null)} onAccept={acceptConsentAndGenerate}/>}
  </div>
}

function GoalAIConsentModal({consent,onClose,onAccept}:{consent:AIConsent;onClose:()=>void;onAccept:()=>Promise<void>}){
  const [checked,setChecked]=useState(false);const [privacy,setPrivacy]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const accept=async()=>{if(!checked)return;setSaving(true);setError('');try{await onAccept()}catch(err){setError(err instanceof Error?err.message:'Не удалось сохранить согласие')}finally{setSaving(false)}}
  return <><Modal title="Согласие на использование GigaChat" onClose={onClose}><div className="goal-consent-dialog"><span className="goal-consent-icon"><ShieldCheck/></span><h3>Разрешить составление персонального плана?</h3><p>Для подготовки плана GigaChat получит описание цели и минимально необходимый контекст: события, задачи, привычки, показатели нагрузки и рабочие настройки.</p><button type="button" className="privacy-link inline" onClick={()=>setPrivacy(true)}>Прочитать политику конфиденциальности</button><label className="consent-check"><input type="checkbox" checked={checked} onChange={event=>setChecked(event.target.checked)}/><span>Я ознакомился(ась) с политикой версии {consent.policy_version} и явно соглашаюсь на описанную передачу данных в GigaChat.</span></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Отмена</button><button type="button" className="primary" disabled={!checked||saving} onClick={()=>void accept()}>{saving?'Сохраняем…':'Согласиться и составить план'}</button></div></div></Modal>{privacy&&<PrivacyPolicy onClose={()=>setPrivacy(false)}/>}</>
}

function GoalAIPlan({plan,onApply,onEdit,onRegenerate,onDiscuss,onCancel}:{plan:GoalPlan;onApply:()=>void;onEdit:()=>void;onRegenerate:()=>void;onDiscuss:()=>void;onCancel:()=>void}){
  const data=plan.plan
  return <section className="goal-ai-plan"><header><span><Sparkles/> AI-план · версия {plan.version}</span><em>{plan.status==='applied'?'Применён':'Черновик'}</em></header><h4>{data.goal_summary}</h4><p>{data.strategy}</p>
    {plan.diff&&<div className="plan-diff"><b>Что изменилось</b><span>Добавлено: {plan.diff.added.length} · Удалено: {plan.diff.removed.length} · Перенесено: {plan.diff.moved.length}</span><small>{plan.diff.reason}</small></div>}
    <div className="plan-sections">
      <details open><summary><b>Этапы</b><span>{data.milestones.length}</span><ChevronDown/></summary>{data.milestones.map((item,index)=><article key={index}><CheckCircle2/><span>{item.title}<small>до {ruDate(item.deadline)} · {item.success_criteria[0]}</small></span></article>)}</details>
      <details open><summary><b>Задачи</b><span>{data.tasks.length}</span><ChevronDown/></summary>{data.tasks.map((item,index)=><article key={index}><CheckSquare2/><span>{item.title}<small>{item.estimated_minutes} мин · {item.deadline?`до ${ruDate(item.deadline)}`:'без срока'}</small></span></article>)}</details>
      <details open><summary><b>Привычки</b><span>{data.habits.length}</span><ChevronDown/></summary>{data.habits.map((item,index)=><article key={index}><Flame/><span>{item.title}<small>{item.frequency} · {item.duration_minutes} мин</small></span></article>)}</details>
      <details><summary><b>Недельный ритм</b><span>{data.weekly_plan.length}</span><ChevronDown/></summary>{data.weekly_plan.map((item,index)=><article key={index}><CalendarDays/><span>{item.action}<small>{item.day_of_week} · {item.duration_minutes} мин</small></span></article>)}</details>
    </div>
    <div className="plan-insights"><div><b>Риски</b>{data.risks.map((item,index)=><p key={index}><AlertTriangle/> {item.risk}: {item.mitigation}</p>)}</div><div><b>Метрики</b>{data.progress_metrics.map((item,index)=><p key={index}><TrendingUp/> {item.name}: {item.target}</p>)}</div><strong><Sparkles/> Первый шаг: {data.first_next_action.title} · {data.first_next_action.estimated_minutes} мин</strong></div>
    <footer><button className="primary" onClick={onApply}>Применить весь план</button><button onClick={onApply}>Применить выбранные пункты</button><button onClick={onEdit}>Изменить план</button><button onClick={onRegenerate}>Составить заново</button><button onClick={onDiscuss}>Обсудить план с AI</button><button onClick={onCancel}>Отменить</button></footer>
  </section>
}

const planGroups:[keyof Pick<GoalPlanPayload,'milestones'|'tasks'|'habits'|'schedule_suggestions'>,string][]=[['milestones','Этапы цели'],['tasks','Задачи'],['habits','Привычки'],['schedule_suggestions','Календарные блоки']]
function PlanApplyModal({goal,plan,onClose,onApplied}:{goal:Goal;plan:GoalPlan;onClose:()=>void;onApplied:()=>void}){
  const initial=Object.fromEntries(planGroups.map(([key])=>[key,plan.plan[key].map((_,index)=>index)])) as Record<string,number[]>
  const [selected,setSelected]=useState<Record<string,number[]>>(initial);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const toggle=(key:string,index:number)=>setSelected(prev=>({...prev,[key]:prev[key].includes(index)?prev[key].filter(item=>item!==index):[...prev[key],index]}))
  const apply=async()=>{setSaving(true);setError('');try{const components=planGroups.map(([key])=>key).filter(key=>selected[key].length);await api(`/goals/${goal.id}/plan/apply`,{method:'POST',body:JSON.stringify({confirm:true,components,selected_indices:selected})});onApplied()}catch(err){setError(err instanceof Error?err.message:'Не удалось применить план')}finally{setSaving(false)}}
  const itemTitle=(item:unknown)=>typeof item==='object'&&item!==null&&'title' in item?String((item as {title:string}).title):'Пункт плана'
  return <Modal title="Предпросмотр изменений" onClose={onClose}><div className="plan-preview"><p>Axel One создаст только отмеченные сущности. Старый план и существующие данные не удаляются.</p>{planGroups.map(([key,label])=><section key={key}><b>{label}</b>{plan.plan[key].map((item,index)=><label key={index}><input type="checkbox" checked={selected[key].includes(index)} onChange={()=>toggle(key,index)}/><span>{itemTitle(item)}</span></label>)}</section>)}{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="secondary" onClick={onClose}>Отменить</button><button className="primary" disabled={saving||!Object.values(selected).some(items=>items.length)} onClick={()=>void apply()}>{saving?'Применяю…':'Подтвердить применение'}</button></div></div></Modal>
}

function GoalModal({timezone,onClose,onSaved}:{timezone:string;onClose:()=>void;onSaved:()=>void}){
  const target=new Date();target.setMonth(target.getMonth()+3)
  const [form,setForm]=useState({title:'',description:'',horizon:'quarter',target_date:calendarDateInTimeZone(timezone,target)});const [error,setError]=useState('')
  const submit=async(e:React.FormEvent)=>{e.preventDefault();try{await api<Goal>('/goals',{method:'POST',body:JSON.stringify(form)});onSaved()}catch(err){setError(err instanceof Error?err.message:'Ошибка')}}
  return <Modal title="Новая цель" onClose={onClose}><form className="modal-form" onSubmit={submit}><label className="full">Результат<input autoFocus required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Чего вы хотите достичь?"/></label><label className="full">Почему это важно<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Контекст поможет сделать план точнее"/></label><label>Горизонт<select value={form.horizon} onChange={e=>setForm({...form,horizon:e.target.value})}><option value="month">Месяц</option><option value="quarter">Квартал</option><option value="year">Год</option><option value="long_term">Долгосрочно</option></select></label><label>Целевая дата<input type="date" value={form.target_date} onChange={e=>setForm({...form,target_date:e.target.value})}/></label><div className="goal-auto-note full"><Sparkles/> Axel AI может автоматически подготовить черновик плана. Для GigaChat приложение сначала запросит согласие; изменения применятся только после вашего подтверждения.</div>{error&&<div className="form-error full">{error}</div>}<div className="modal-actions full"><button type="button" className="secondary" onClick={onClose}>Отмена</button><button className="primary"><Sparkles/> Создать цель</button></div></form></Modal>
}

export function HabitsPage({timezone,onChanged}:{timezone:string;onChanged:()=>void}){
  const [habits,setHabits]=useState<Habit[]|null>(null);const [modal,setModal]=useState(false)
  const load=()=>api<Habit[]>('/habits').then(setHabits);useEffect(()=>{void load()},[])
  const toggle=async(item:Habit)=>{const today=calendarDateInTimeZone(timezone);if(item.completed_today)await api(`/habits/${item.id}/checkins/${today}`,{method:'DELETE'});else await api(`/habits/${item.id}/checkins`,{method:'POST',body:JSON.stringify({checkin_date:today})});load();onChanged()}
  const archive=async(id:number)=>{await api(`/habits/${id}`,{method:'PATCH',body:JSON.stringify({archived:true})});load();onChanged()}
  if(!habits)return <Loading/>
  const completed=habits.filter(h=>h.completed_today).length
  return <div className="page"><PageHeader eyebrow="Маленькие действия, большой эффект" title="Привычки" description="Не стремитесь к идеальной серии — создавайте ритм, к которому легко возвращаться." action={<button className="primary" onClick={()=>setModal(true)}><Plus/> Добавить привычку</button>}/>
    <section className="habit-hero"><div className="habit-score"><div><b>{completed}</b><span>из {habits.length}</span></div><p>выполнено сегодня</p></div><div className="week-visual"><span>Ваш ритм на этой неделе</span><div>{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((day,index)=><i key={day} className={index<new Date().getDay()?'past':index===new Date().getDay()-1?'today':''}><b>{day}</b><em>{index<Math.max(1,new Date().getDay()-1)?<Check/>:''}</em></i>)}</div></div><div className="habit-tip"><Flame/><span><b>Серия — не цель</b><small>Главное — вернуться на следующий день.</small></span></div></section>
    <section className="habit-grid">{habits.length?habits.map(item=><article className={`habit-card ${item.completed_today?'done':''}`} key={item.id} style={{'--habit':item.color} as React.CSSProperties}><div className="habit-card-head"><span>{item.emoji}</span><button className="icon-btn" onClick={()=>archive(item.id)}><X/></button></div><h3>{item.title}</h3><p>{item.target_per_week} раз в неделю</p><div className="habit-stats"><span><Flame/><b>{item.current_streak}</b><small>текущая серия</small></span><span><TrendingUp/><b>{item.best_streak}</b><small>лучший результат</small></span></div><div className="progress"><i style={{width:`${Math.min(100,item.week_count/item.target_per_week*100)}%`}}/></div><button className="habit-complete" onClick={()=>toggle(item)}>{item.completed_today?<><CheckCircle2/> Выполнено сегодня</>:<><Circle/> Отметить выполнение</>}</button></article>):<div className="card"><Empty icon={Flame} title="Создайте свой ритм" text="Начните с одной привычки, которую легко выполнить даже в загруженный день."/></div>}</section>
    {modal&&<HabitModal onClose={()=>setModal(false)} onSaved={()=>{setModal(false);load();onChanged()}}/>}
  </div>
}

function HabitModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState({title:'',emoji:'✨',cadence:'daily',target_per_week:7,color:'#00B894'})
  const submit=async(e:React.FormEvent)=>{e.preventDefault();await api('/habits',{method:'POST',body:JSON.stringify(form)});onSaved()}
  return <Modal title="Новая привычка" onClose={onClose}><form className="modal-form" onSubmit={submit}><label className="full">Название<input autoFocus required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Например, вечерняя прогулка"/></label><label>Символ<input maxLength={4} value={form.emoji} onChange={e=>setForm({...form,emoji:e.target.value})}/></label><label>Цель в неделю<input type="number" min="1" max="7" value={form.target_per_week} onChange={e=>setForm({...form,target_per_week:+e.target.value})}/></label><label>Ритм<select value={form.cadence} onChange={e=>setForm({...form,cadence:e.target.value})}><option value="daily">Каждый день</option><option value="weekdays">По будням</option><option value="weekly">Раз в неделю</option></select></label><label>Цвет<input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label><div className="modal-actions full"><button type="button" className="secondary" onClick={onClose}>Отмена</button><button className="primary">Добавить</button></div></form></Modal>
}

const balanceLabels:Record<string,string>={health:'Здоровье',career:'Карьера',finance:'Финансы',relationships:'Отношения',growth:'Развитие',recreation:'Отдых',environment:'Окружение',contribution:'Вклад'}

export function AnalyticsPage({timezone}:{timezone:string}){
  const [analytics,setAnalytics]=useState<Analytics|null>(null);const [balance,setBalance]=useState<Balance[]>([]);const [recs,setRecs]=useState<Recommendation[]>([]);const [assessment,setAssessment]=useState(false)
  const load=()=>Promise.all([api<Analytics>('/analytics?days=30'),api<Balance[]>('/balance'),api<Recommendation[]>('/recommendations')]).then(([a,b,r])=>{setAnalytics(a);setBalance(b);setRecs(r)})
  useEffect(()=>{void load()},[])
  const generate=async()=>{await api('/recommendations/generate',{method:'POST'});load()}
  if(!analytics)return <Loading/>
  const latest=balance[0];const maxDay=Math.max(1,...analytics.productive_days.map(d=>d.completed))
  return <div className="page"><PageHeader eyebrow="От данных к ясности" title="Аналитика и баланс" description="Смотрите не только на сделанное, но и на цену, которую вы за это платите." action={<button className="secondary" onClick={()=>setAssessment(true)}><HeartPulse/> Оценить баланс</button>}/>
    <section className="analytics-metrics"><Metric icon={CheckCircle2} color="mint" value={analytics.tasks_completed} label="Задач завершено" note={`${analytics.task_completion_rate}% от созданных`}/><Metric icon={Brain} color="violet" value={`${Math.round(analytics.focus_minutes/60)} ч`} label="Сфокусированной работы" note="По оценке задач"/><Metric icon={Flame} color="orange" value={`${analytics.habit_completion_rate}%`} label="Ритм привычек" note="За последние 30 дней"/><Metric icon={Activity} color="blue" value={analytics.balance_score||'—'} label="Баланс жизни" note="Из 10 баллов"/></section>
    <div className="analytics-grid"><section className="card chart-card"><CardHead icon={BarChart3} title="Динамика завершений" subtitle="Последние 14 дней"/><div className="bar-chart">{analytics.productive_days.map(day=><div key={day.date}><i style={{height:`${Math.max(8,day.completed/maxDay*100)}%`}}><em>{day.completed}</em></i><span>{new Date(`${day.date}T12:00`).toLocaleDateString('ru-RU',{weekday:'short'}).slice(0,2)}</span></div>)}</div></section>
      <section className="card balance-card"><CardHead icon={HeartPulse} title="Колесо баланса" subtitle={latest?`Оценка ${ruDate(latest.assessment_date)}`:'Нет оценки'}/>{latest?<div className="balance-bars">{Object.entries(balanceLabels).map(([key,label])=><div key={key}><span>{label}</span><div><i style={{width:`${(latest as unknown as Record<string,number>)[key]*10}%`}}/></div><b>{(latest as unknown as Record<string,number>)[key]}</b></div>)}</div>:<Empty icon={HeartPulse} title="Добавьте оценку" text="Восемь быстрых вопросов покажут, где сейчас нужен ресурс."/>}</section>
    </div>
    <section className="card recommendations"><div className="recommendation-head"><div><span className="ai-orb"><Sparkles/></span><div><h3>Персональные рекомендации</h3><p>Сформированы по вашему реальному плану и прогрессу.</p></div></div><button className="secondary" onClick={generate}><RefreshCw/> Обновить</button></div><div className="recommendation-grid">{recs.filter(r=>r.status==='new').slice(0,3).map(item=><article key={item.id}><span>{item.kind==='overload'?<AlertTriangle/>:item.kind==='habits'?<Flame/>:<Sparkles/>}</span><small>{item.kind}</small><h4>{item.title}</h4><p>{item.body}</p><button onClick={async()=>{await api(`/recommendations/${item.id}`,{method:'PATCH',body:JSON.stringify({status:'done'})});load()}}>{item.action||'Принять'} <ArrowRight/></button></article>)}</div></section>
    {assessment&&<BalanceModal timezone={timezone} onClose={()=>setAssessment(false)} onSaved={()=>{setAssessment(false);load()}}/>}
  </div>
}

function BalanceModal({timezone,onClose,onSaved}:{timezone:string;onClose:()=>void;onSaved:()=>void}){
  const [values,setValues]=useState<Record<string,number>>(Object.fromEntries(Object.keys(balanceLabels).map(key=>[key,7])))
  const submit=async(e:React.FormEvent)=>{e.preventDefault();await api('/balance',{method:'POST',body:JSON.stringify({...values,assessment_date:calendarDateInTimeZone(timezone)})});onSaved()}
  return <Modal title="Колесо жизненного баланса" onClose={onClose}><form className="balance-form" onSubmit={submit}><p>Оцените, насколько вы довольны каждой сферой прямо сейчас.</p>{Object.entries(balanceLabels).map(([key,label])=><label key={key}><span>{label}</span><input type="range" min="1" max="10" value={values[key]} onChange={e=>setValues({...values,[key]:+e.target.value})}/><b>{values[key]}</b></label>)}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Отмена</button><button className="primary">Сохранить оценку</button></div></form></Modal>
}

export function SettingsPage({user,onUser,onTheme}:{user:User;onUser:(user:User)=>void;onTheme:(theme:ThemePreference)=>void}){
  const [settings,setSettings]=useState<Settings|null>(null)
  const [consent,setConsent]=useState<AIConsent|null>(null)
  const [profile,setProfile]=useState({name:user.name,occupation:user.occupation||'',timezone:user.timezone})
  const [saved,setSaved]=useState(false)
  const [consentChecked,setConsentChecked]=useState(false)
  const [privacy,setPrivacy]=useState(false)
  const [accountMessage,setAccountMessage]=useState('')
  const [deleteForm,setDeleteForm]=useState({password:'',confirmation:''})
  useEffect(()=>{void Promise.all([api<Settings>('/settings').then(setSettings),api<AIConsent>('/settings/ai-consent').then(setConsent)])},[])
  if(!settings||!consent)return <Loading/>
  const save=async(e:React.FormEvent)=>{e.preventDefault();const [updated,updatedSettings]=await Promise.all([api<User>('/auth/me',{method:'PATCH',body:JSON.stringify(profile)}),api<Settings>('/settings',{method:'PATCH',body:JSON.stringify(settings)})]);onUser(updated);onTheme(updatedSettings.theme as ThemePreference);setSaved(true);setTimeout(()=>setSaved(false),1800)}
  const acceptConsent=async()=>{if(!consentChecked)return;setConsent(await api<AIConsent>('/settings/ai-consent',{method:'POST',body:JSON.stringify({accepted:true,policy_version:consent.policy_version})}));setConsentChecked(false)}
  const revokeConsent=async()=>setConsent(await api<AIConsent>('/settings/ai-consent',{method:'DELETE'}))
  const verifyEmail=async()=>{const result=await api<{message:string}>('/auth/request-email-verification',{method:'POST'});setAccountMessage(result.message)}
  const exportData=async()=>{await downloadAccountExport();setAccountMessage('Экспорт подготовлен и загружен.')}
  const deleteAccount=async()=>{setAccountMessage('');try{await api('/account',{method:'DELETE',body:JSON.stringify(deleteForm)});session.clear();location.reload()}catch(error){setAccountMessage(error instanceof Error?error.message:'Не удалось удалить аккаунт')}}
  return <div className="page"><PageHeader eyebrow="Ваше пространство" title="Профиль и настройки" description="Настройте Axel One под свой ритм, рабочие часы и стиль рекомендаций."/>
    <form className="settings-layout" onSubmit={save}><section className="card settings-section"><div className="settings-title"><span><Settings2/></span><div><h3>Профиль</h3><p>Эти данные используются в приветствии и рекомендациях.</p></div></div><div className="settings-fields"><label>Имя<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Роль или занятие<input value={profile.occupation} onChange={e=>setProfile({...profile,occupation:e.target.value})}/></label><label className="full">Часовой пояс<input value={profile.timezone} onChange={e=>setProfile({...profile,timezone:e.target.value})}/></label></div></section>
      <section className="card settings-section"><div className="settings-title"><span><Clock3/></span><div><h3>Ритм работы</h3><p>Границы помогают точнее замечать перегрузку.</p></div></div><div className="settings-fields"><label>Начало дня<input type="time" value={settings.workday_start} onChange={e=>setSettings({...settings,workday_start:e.target.value})}/></label><label>Конец дня<input type="time" value={settings.workday_end} onChange={e=>setSettings({...settings,workday_end:e.target.value})}/></label><label>Фокус-часов в неделю<input type="number" min="1" max="80" value={settings.weekly_focus_hours} onChange={e=>setSettings({...settings,weekly_focus_hours:+e.target.value})}/></label><label>Ежедневный обзор<input type="time" value={settings.daily_digest_time} onChange={e=>setSettings({...settings,daily_digest_time:e.target.value})}/></label></div></section>
      <section className="card settings-section"><div className="settings-title"><span><Sparkles/></span><div><h3>Интерфейс и AI</h3><p>Выберите комфортный тон и визуальный режим.</p></div></div><div className="theme-options">{([{id:'dark',icon:Moon,label:'Тёмная'},{id:'system',icon:Settings2,label:'Системная'},{id:'light',icon:Sun,label:'Светлая'}] as const).map(item=><button type="button" key={item.id} className={settings.theme===item.id?'active':''} onClick={()=>{setSettings({...settings,theme:item.id});onTheme(item.id)}}><item.icon/><span>{item.label}</span>{settings.theme===item.id&&<Check/>}</button>)}</div><div className="settings-fields"><label>Тон помощника<select value={settings.ai_tone} onChange={e=>setSettings({...settings,ai_tone:e.target.value})}><option value="supportive">Поддерживающий</option><option value="direct">Прямой</option><option value="coach">Коуч</option></select></label><label className="toggle-label"><span><b>Уведомления</b><small>Напоминания и дневной обзор</small></span><input type="checkbox" checked={settings.notifications_enabled} onChange={e=>setSettings({...settings,notifications_enabled:e.target.checked})}/><i/></label></div></section>
      <section className="card settings-section consent-section"><div className="settings-title"><span><ShieldCheck/></span><div><h3>Передача контекста в GigaChat</h3><p>{consent.active?'Согласие действует. Вы можете отозвать его в любой момент.':'Без отдельного согласия сервер не отправляет персональный контекст в GigaChat.'}</p></div></div><div className="consent-copy"><p>При облачном AI передаются ваш вопрос и минимально необходимый контекст: события, задачи, цели, привычки, показатели нагрузки и рабочие настройки. Цель — сформировать персональный ответ.</p><button type="button" className="privacy-link inline" onClick={()=>setPrivacy(true)}>Прочитать политику конфиденциальности</button>{!consent.active?<><label className="consent-check"><input type="checkbox" checked={consentChecked} onChange={e=>setConsentChecked(e.target.checked)}/><span>Я ознакомился(ась) с политикой версии {consent.policy_version} и явно соглашаюсь на описанную передачу данных в GigaChat.</span></label><button type="button" className="secondary" disabled={!consentChecked} onClick={()=>void acceptConsent()}>Дать согласие</button></>:<button type="button" className="danger-button" onClick={()=>void revokeConsent()}>Отозвать согласие</button>}</div></section>
      <section className="card settings-section account-section"><div className="settings-title"><span><Download/></span><div><h3>Данные и аккаунт</h3><p>Экспортируйте данные или безвозвратно удалите аккаунт.</p></div></div><div className="account-tools">{!user.email_verified&&<div className="account-row"><div><b>Email не подтверждён</b><p>Подтверждение защищает восстановление доступа.</p></div><button type="button" className="secondary" onClick={()=>void verifyEmail()}>Отправить ссылку</button></div>}<div className="account-row"><div><b>Экспорт JSON</b><p>Профиль, календарь, задачи, цели, привычки, аналитика и AI-история.</p></div><button type="button" className="secondary" onClick={()=>void exportData()}><Download/> Скачать</button></div><div className="delete-account"><div><UserX/><span><b>Удалить аккаунт</b><small>Все сессии будут отозваны, связанные данные удалены.</small></span></div><div className="settings-fields"><label>Текущий пароль<input type="password" value={deleteForm.password} onChange={e=>setDeleteForm({...deleteForm,password:e.target.value})}/></label><label>Введите DELETE<input value={deleteForm.confirmation} onChange={e=>setDeleteForm({...deleteForm,confirmation:e.target.value})}/></label></div><button type="button" className="danger-button" disabled={!deleteForm.password||deleteForm.confirmation!=='DELETE'} onClick={()=>void deleteAccount()}><Trash2/> Удалить безвозвратно</button></div>{accountMessage&&<p className="account-message">{accountMessage}</p>}</div></section>
      <div className="settings-actions"><span>{saved?<><CheckCircle2/> Настройки сохранены</>:''}</span><button className="primary">Сохранить изменения</button></div>
    </form>
    {privacy&&<PrivacyPolicy onClose={()=>setPrivacy(false)}/>}
  </div>
}
